const fs = require('fs');
const path = require('path');

const textPath = path.join(__dirname, '..', '..', '!PhoneDrop', 'text.txt');
const text = fs.readFileSync(textPath, 'utf8');
const lines = text.trim().split('\n').filter(l => l.trim());
const songs = [];
let singer = '';

for (const line of lines) {
  if (line.trim().startsWith('_')) {
    singer = line.trim().replace(/^_+/, '').trim();
    continue;
  }
  const match = line.match(/^(\d+)\s*[-–]\s*(.+?)\s*\(([A-G][#b]?[mM]?-?)\)\s*$/);
  if (!match) continue;
  const [, num, titleRaw, key] = match;
  let title = titleRaw.trim();
  let project = '';
  let bpm = '';
  const pm = title.match(/^(.+?)\(([^)]+)\)\s*$/);
  if (pm) {
    title = pm[1].trim();
    const tag = pm[2].trim();
    const bm = tag.match(/(\d+)\s*bpm/i);
    if (bm) { bpm = bm[1]; project = tag.replace(/\d+\s*bpm/i, '').trim(); }
    else { project = tag; }
  }
  title = title.replace(/\s+\d+\s+\d+\s*$/, '').trim().replace(/\s+[12]$/, '').trim();
  const normKey = key.replace('m', '-').replace('M', '');
  songs.push({
    id: 'seed_' + songs.length,
    title, key: normKey, bpm,
    singer: singer || '', project: project || '',
    genre: '', // assigned manually — see SEED_GENRES in index.html
    notes: ''
  });
}

const htmlPath = path.join(__dirname, 'index.html');
let html = fs.readFileSync(htmlPath, 'utf8');
const seedData = JSON.stringify(songs);

// Replace between markers
const startMarker = '// >>> SEED_DATA_START (auto-generated by seed.js)';
const endMarker = '// <<< SEED_DATA_END';
const startIdx = html.indexOf(startMarker);
const endIdx = html.indexOf(endMarker);

if (startIdx >= 0 && endIdx >= 0) {
  const before = html.slice(0, startIdx + startMarker.length);
  const after = html.slice(endIdx);
  const middle = '\n  const SEED_DATA = ' + seedData + ';\n\n  // Apply genre assignments to seed data\n  SEED_DATA.forEach((song, i) => {\n    song.genre = SEED_GENRES[i] || \'\';\n  });\n  ';
  html = before + middle + after;
  fs.writeFileSync(htmlPath, html);
  console.log('Seeded ' + songs.length + ' songs into index.html');
} else {
  console.error('Could not find SEED_DATA markers in index.html');
  process.exit(1);
}
